#definition of secret for mysql root password
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword | b64enc }}

  #MYSQL_ROOT_PASSWORD: am9rZW9mYXBhc3N3b3JkCg==
  