apiVersion: v1
kind: ResourceQuota
metadata:
  name: wordpress-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "6"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "3"
    limits.memory: "2Gi"
    services: "4"