apiVersion: v1
kind: ResourceQuota
metadata:
  name: wordpress-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    services: "3"